name: nginx
version: 2.1.2
appVersion: 1.14.2
description: Modified version of Helm chart - changed Deployment resource version to 'v1'
keywords:
- nginx
- http
- web
- www
- reverse proxy
home: http://www.nginx.org
icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
sources:
- https://github.com/bitnami/bitnami-docker-nginx
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
